title: "Instalguru"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://instalguru.co.uk" # the base hostname & protocol for your site, e.g. http://example.com
lang: "en"
photo: "/assets/img/default.jpg"

markdown: kramdown

remote_theme: arturmatlega/ig-theme

toc:
  min_level: 2
  max_level: 3

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-toc
  - jekyll-remote-theme

ampdir: amp

collections:
  posts:    
    permalink: /blog/:title:output_ext