title: "Instalguru"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://instalguru.it" # the base hostname & protocol for your site, e.g. http://example.com
lang: "it"
photo: "/assets/img/default.jpg"
scvarificationnumber: "xVrOy1Ahzwj9lNe9bkT2LDiH7wWLcZu463ec2eoCs4o" # numer identyfikacjyny google search console
analyticsvarificationnumber: "UA-145248341-7" # numer identyfikacjyny google analyticks
gtagmanagervarificationnumber:
optimizevarificationnumber:
facebookpixelnumber: "438112533832846" 

markdown: kramdown

remote_theme: arturmatlega/ig-theme

toc:
  min_level: 2
  max_level: 3

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-toc
  - jekyll-remote-theme

ampdir: amp

collections:
  posts:    
    permalink: /blog/:title:output_ext